Fix/always restart service
Telaqua/gateway_tailscale pull request #2
Opened 2024-03-08 10:22 UTC by mickalaqua

Make sure the process is always running by changing init.d configuration. 

The modification is not explicit because the changes is done the packages.

This changes the line in /etc/init.d/tailscale from : "procd_set_param" respawn to "procd_set_param respawn 5 10 0". This force init.d to retry to run the process for an infinite number of times.

When installing the package using opkg on RAK7289C and RAK7249 the file /etc/init.d/tailscale is modified as expected.
However, it is not possible to reinstall the package on RAK7289CV2 due to a space issue. Even when, the original tailscale.combined binary is deleted before downloading the new one, it seems that the space available from the original binary is not reclaim. Then when new binary is downloaded the gateway run out of space and the process stops. A gateway reboot is mandatory to reclaim the space used by the original binary.

For this reason the file /etc/init.d/tailscale will be modified manually on RAK7289CV2 gateways

2024-03-11 06:59 UTC, jfponstelaqua requested changes
@mickalaqua I do not have any way to test it so I rely on you for it to be valid and tested on a gateway. I think the process used to build the binary should also be commited somewhere for anyone to be able to recompile it.

I just requested a change for the Pipfile to be removed for this PR, then you can merge the content.

PS: Please do not forget to "resolve" the review elements.

2024-03-11 06:59 UTC, jfponstelaqua commented on Pipfile
@mickalaqua I don't get why this file is part of this merge request since there is no Python file here -> that should be removed from this PR

2024-03-11 12:12 UTC, mickalaqua commented on Pipfile
@jfponstelaqua I removed the pip file and added the script used to generate the packages.
I keep the PR open in case you want to review the script

2024-03-13 06:42 UTC, jfponstelaqua commented
@mickalaqua Thanks for the script. I do not have time right now to review it but since it is already used in production I accpet it as is and we will proceed to review if we found bugs

2024-03-13 06:42 UTC, merged